from fastapi import APIRouter, Header, HTTPException, Query
from typing import List, Optional

from .free_courses_catalogue import FREE_COURSE_CATALOGUE, get_free_course_by_id

router = APIRouter(prefix="/courses", tags=["Courses"])

# Optional browse/search catalogue (not used for home recommendations).
COURSE_CATALOGUE: List[dict] = FREE_COURSE_CATALOGUE

router_obj = router


def get_course_by_id(course_id: str):
    """Resolve a course from the static catalogue (weekly plan by id only)."""
    return get_free_course_by_id(course_id)


@router.get("/all")
async def get_all_courses(language: Optional[str] = None, is_free: Optional[bool] = None):
    """Browse curated free catalogue (optional)."""
    result = list(COURSE_CATALOGUE)
    if language:
        result = [c for c in result if c.get("language", "").lower() == language.lower()]
    if is_free is not None:
        result = [c for c in result if c.get("is_free") is True]
    return {"courses": result, "count": len(result)}


@router.get("/recommend/{uid}")
async def recommend_courses_for_user(
    uid: str,
    client: Optional[str] = Query(
        default=None,
        description="Set to job_finder for AI recommendations (job finder home).",
    ),
    x_naviudan_client: Optional[str] = Header(default=None, alias="X-NaviUdan-Client"),
):
    """
    Personalized FREE course recommendations generated by the backend LLM from the user's profile.
    Intended for the job finder home after onboarding. Other clients should omit or not call this.
    """
    from services.firebase_service import get_document
    from services.gemini_service import openrouter_recommend_free_courses_from_profile

    is_job_finder = (client or "").strip().lower() == "job_finder" or (
        (x_naviudan_client or "").strip().lower() == "job_finder"
    )
    if not is_job_finder:
        raise HTTPException(
            status_code=400,
            detail="Pass client=job_finder or header X-NaviUdan-Client: job_finder (job finder only).",
        )

    user = await get_document("users", uid)
    if not user:
        raise HTTPException(
            status_code=404,
            detail="Complete your profile first — then open the job finder home to load recommendations.",
        )

    skills = user.get("skills", []) or []
    interests = user.get("interests", []) or []
    if not skills and not interests:
        return {
            "courses": [],
            "message": "Add skills or interests to your profile to get tailored free course picks.",
            "uid": uid,
        }

    lang = user.get("preferred_language") or user.get("language") or "English"

    ai = await openrouter_recommend_free_courses_from_profile(skills, interests, str(lang))
    if ai is not None:
        picked, msg = ai
        note = "Links are AI-suggested free resources; verify in browser. Some sites need a free account."
        full_msg = f"{msg} {note}".strip() if msg else note
        return {"courses": picked, "message": full_msg, "uid": uid}

    return {
        "courses": [],
        "message": "AI recommendations are unavailable (check OPENROUTER_API_KEY and credits).",
        "uid": uid,
    }


@router.get("/search")
async def search_courses(q: str):
    """Search curated catalogue by keyword."""
    q_lower = q.lower()
    results = [
        c
        for c in COURSE_CATALOGUE
        if q_lower in c.get("title", "").lower()
        or any(q_lower in tag.lower() for tag in c.get("tags", []))
    ]
    return {"courses": results, "count": len(results)}
