"""
Curated free learning resources with real URLs (YouTube, OCW, Google Digital Garage, NPTEL, etc.).
All entries are free to access; some platforms require a free account.
"""

from typing import Any, Dict, List, Optional

FREE_COURSE_CATALOGUE: List[Dict[str, Any]] = [
    {
        "id": "f1",
        "title": "CS50 Introduction to Computer Science (Harvard)",
        "platform": "Harvard / edX-style",
        "url": "https://cs50.harvard.edu/x/2024/",
        "language": "English",
        "tags": ["programming", "computer science", "beginner", "c", "python"],
        "is_free": True,
        "duration": "11 weeks (self-paced)",
        "description": "Harvard's intro CS course — algorithms, C, Python, web basics.",
    },
    {
        "id": "f2",
        "title": "MIT OCW — Intro to CS and Programming in Python",
        "platform": "MIT OpenCourseWare",
        "url": "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
        "language": "English",
        "tags": ["python", "programming", "algorithms", "beginner"],
        "is_free": True,
        "duration": "Semester-length",
        "description": "MIT lectures, notes, and assignments — Python foundations.",
    },
    {
        "id": "f3",
        "title": "Python for Beginners — Full Course (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
        "language": "English",
        "tags": ["python", "programming", "beginner"],
        "is_free": True,
        "duration": "~4.5 hours",
        "description": "Hands-on Python basics on YouTube.",
    },
    {
        "id": "f4",
        "title": "JavaScript Full Course for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        "language": "English",
        "tags": ["javascript", "web development", "programming", "frontend"],
        "is_free": True,
        "duration": "~3.5 hours",
        "description": "JS fundamentals through small projects.",
    },
    {
        "id": "f5",
        "title": "HTML Full Course — Build a Website (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=pQN-pnXPaVg",
        "language": "English",
        "tags": ["html", "web development", "frontend", "beginner"],
        "is_free": True,
        "duration": "~2 hours",
        "description": "HTML structure and semantics.",
    },
    {
        "id": "f6",
        "title": "CSS Full Course — Includes Flexbox & Grid (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=ieTHC78giGQ",
        "language": "English",
        "tags": ["css", "web development", "frontend", "design"],
        "is_free": True,
        "duration": "~6 hours",
        "description": "Styling and layout with CSS.",
    },
    {
        "id": "f7",
        "title": "Full Web Development Course — HTML, CSS, JavaScript (YouTube)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=mU6anWqZJcc",
        "language": "English",
        "tags": ["web development", "html", "css", "javascript", "frontend"],
        "is_free": True,
        "duration": "~11 hours",
        "description": "End-to-end beginner web dev on one playlist-style course.",
    },
    {
        "id": "f8",
        "title": "React Course — Beginner's Tutorial (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=bMknfKXIFA8",
        "language": "English",
        "tags": ["react", "javascript", "web development", "frontend"],
        "is_free": True,
        "duration": "~11 hours",
        "description": "React components, hooks, and small apps.",
    },
    {
        "id": "f9",
        "title": "Flutter Course for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=VPvVD8t02U8",
        "language": "English",
        "tags": ["flutter", "dart", "mobile", "app development"],
        "is_free": True,
        "duration": "~37 hours",
        "description": "Build cross-platform apps with Flutter.",
    },
    {
        "id": "f10",
        "title": "Git and GitHub for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=RGOj5yH7evk",
        "language": "English",
        "tags": ["git", "github", "programming", "tools"],
        "is_free": True,
        "duration": "~1 hour",
        "description": "Version control essentials.",
    },
    {
        "id": "f11",
        "title": "SQL Tutorial — Full Database Course for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        "language": "English",
        "tags": ["sql", "database", "data analysis", "backend"],
        "is_free": True,
        "duration": "~4 hours",
        "description": "SQL queries, joins, and design basics.",
    },
    {
        "id": "f12",
        "title": "Excel Tutorial for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=Vl0H-qTclOg",
        "language": "English",
        "tags": ["excel", "data analysis", "office", "business"],
        "is_free": True,
        "duration": "~2 hours",
        "description": "Spreadsheets, formulas, and charts.",
    },
    {
        "id": "f13",
        "title": "Machine Learning for Everybody (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=i_LwzRVP7bg",
        "language": "English",
        "tags": ["machine learning", "ai", "python", "data science"],
        "is_free": True,
        "duration": "~3 hours",
        "description": "Gentle intro to ML concepts and tools.",
    },
    {
        "id": "f14",
        "title": "Google Digital Garage — Fundamentals of Digital Marketing",
        "platform": "Google Digital Garage",
        "url": "https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing",
        "language": "English",
        "tags": ["marketing", "digital", "seo", "business", "sales"],
        "is_free": True,
        "duration": "~40 hours",
        "description": "Free certification course from Google.",
    },
    {
        "id": "f15",
        "title": "Introductory Sales Training (YouTube)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=PHSdMGYZm_4",
        "language": "English",
        "tags": ["sales", "communication", "business", "customer service"],
        "is_free": True,
        "duration": "~2 hours",
        "description": "Sales mindset and basics.",
    },
    {
        "id": "f16",
        "title": "Customer Service Training (YouTube)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=G-QNBL9CNig",
        "language": "English",
        "tags": ["customer service", "communication", "retail", "soft skills"],
        "is_free": True,
        "duration": "~15 min intro + channel series",
        "description": "Professional customer handling tips.",
    },
    {
        "id": "f17",
        "title": "Khan Academy — Computer Programming",
        "platform": "Khan Academy",
        "url": "https://www.khanacademy.org/computing/computer-programming",
        "language": "English",
        "tags": ["programming", "javascript", "html", "beginner"],
        "is_free": True,
        "duration": "Self-paced",
        "description": "Interactive coding lessons.",
    },
    {
        "id": "f18",
        "title": "Khan Academy — Personal Finance",
        "platform": "Khan Academy",
        "url": "https://www.khanacademy.org/college-careers-more/personal-finance",
        "language": "English",
        "tags": ["finance", "business", "math", "career"],
        "is_free": True,
        "duration": "Self-paced",
        "description": "Budgeting, credit, and investing basics.",
    },
    {
        "id": "f19",
        "title": "NPTEL — Programming in C (IIT Kharagpur archive)",
        "platform": "NPTEL",
        "url": "https://archive.nptel.ac.in/courses/106/105/106105171/",
        "language": "English",
        "tags": ["c", "programming", "engineering", "beginner"],
        "is_free": True,
        "duration": "Semester-style",
        "description": "Structured C programming — good for STEM learners.",
    },
    {
        "id": "f20",
        "title": "Linux for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=sWbUDq4S6Y8",
        "language": "English",
        "tags": ["linux", "command line", "it", "tools"],
        "is_free": True,
        "duration": "~2.5 hours",
        "description": "Terminal, files, and permissions.",
    },
    {
        "id": "f21",
        "title": "Data Analysis with Python — Course (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=r-uOLxNrNk8",
        "language": "English",
        "tags": ["python", "data analysis", "pandas", "data science"],
        "is_free": True,
        "duration": "~12 hours",
        "description": "Python stack for analyzing data.",
    },
    {
        "id": "f22",
        "title": "UI / UX Design Course — Beginner to Pro (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=RYJrPBiKGWU",
        "language": "English",
        "tags": ["ux", "ui", "design", "figma", "web"],
        "is_free": True,
        "duration": "~6 hours",
        "description": "Design thinking and practical UX work.",
    },
    {
        "id": "f23",
        "title": "Cybersecurity Course for Beginners (freeCodeCamp)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=U_P23SqJaSo",
        "language": "English",
        "tags": ["cybersecurity", "it", "networking", "security"],
        "is_free": True,
        "duration": "~7 hours",
        "description": "Security fundamentals and careers.",
    },
    {
        "id": "f24",
        "title": "Accounting Basics for Beginners (YouTube)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=pTUeMnoDsOA",
        "language": "English",
        "tags": ["accounting", "finance", "business", "office"],
        "is_free": True,
        "duration": "~1 hour",
        "description": "Debits, credits, and financial statements intro.",
    },
    {
        "id": "f25",
        "title": "Public Speaking — Crash Course (YouTube)",
        "platform": "YouTube",
        "url": "https://www.youtube.com/watch?v=Y9B5PWeUrNU",
        "language": "English",
        "tags": ["communication", "presentation", "soft skills", "teaching"],
        "is_free": True,
        "duration": "~10 min series entry",
        "description": "Crash Course series on public speaking.",
    },
]


def get_free_course_by_id(course_id: str) -> Optional[Dict[str, Any]]:
    cid = str(course_id).strip()
    for c in FREE_COURSE_CATALOGUE:
        if str(c.get("id")) == cid:
            return c
    return None
